package com.halilibrahim.halilibrahim;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.12.12.0
//
// Created by Quasar Development 
//
//----------------------------------------------------



public interface QROIServiceEvents
{
    void Starting();
    void Completed(QROOperationResult result);
}
